---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wakfu.
--- DateTime: 2020/8/1 11:37
---
Orm = {}

function Orm.new(tableName)
    local obj = db_module.new(tableName)
    return obj
end


--*********************go实现的接口api**************************

--获取列表
---@return number|table
function Orm:Raw(execSql)
end

--运行sql
---@return number|table
function Orm:Exec(execSql)
end

--获取标签
---@return number|table
function Orm:Tag()
end

return Orm


