---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wakfu.
--- DateTime: 2020/8/4 17:58
---
local example = {}
--
local json = require('tools.json')
local Http = require('httpRequest.httpRequest')

function example.get()
    local code, response = Http.new():getQuery("https://www.wanandroid.com/hotkey/json")
    if code == 0 then
        local ok, result = pcall(json.decode, response)
        return ok and 0 or -1, result
    else
        return code, response
    end
end

return example