---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wakfu.
--- DateTime: 2020/8/1 11:37
---
Orm = {}

--  开启数据库连接
---@param dialect string 数据库类型
---@param path string 数据库地址
---@param enableLog boolean 是否打开数据库log
function Orm.new(dialect, path, enableLog, tag)
    local obj = db_module.new(dialect, path, enableLog, tag)

    print("新建")
    return obj
end

--  关闭所有数据库连接
function Orm.closeDbByTag(tag)
    local obj = db_module.closeDbByTag(tag)
    print("关闭")
    return obj
end

--  关闭所有数据库连接
function Orm.closeAllDb()
    local obj = db_module.closeAllDb()
    print("关闭")
    return obj
end

print("***********db_module.lua****************")
--*********************go实现的接口api工具类，便于提供代码提示**************************

--获取列表
---@return number|table
function Orm:Raw(execSql)
end

--运行sql
---@return number|table
function Orm:Exec(execSql)
end

--获取标签
---@return number|table
function Orm:Tag()
end

--关闭数据库连接
---@return number|string
function Orm:CloseDB()
end

return Orm


